CREATE TABLE users (
       id       int         GENERATED BY DEFAULT AS IDENTITY,
       username varchar(72) NOT NULL,
       pwdhash  varchar(72),
       PRIMARY KEY(id)
);

CREATE TABLE posts (
       id       int            GENERATED BY DEFAULT AS IDENTITY,
       content  varchar(65536) NOT NULL,
       postdate date,
       userid   int,
       PRIMARY KEY(id)
);

INSERT INTO users (username, pwdhash)
VALUES ('toto', NULL),
       ('dédé', NULL),
       ('paul', NULL);

INSERT INTO posts (userid, content)
VALUES (1, 'salut'),
       (2, 'ça va?'),
       (3, 'ό͔茕뻤넫ߒΜػʭࠔ즾񍂐Ɣ⇨ڑ');
